In [28]:
# Importing libraries...

import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [29]:
genres = pd.read_csv('genres.csv')
genres = genres.dropna()
genres.head()

artists                                     name  \
0  Julia Michaels, Niall Horan          What A Time (feat. Niall Horan)   
1               Camila Cabello                             Don't Go Yet   
2                 Alessia Cara                  Scars To Your Beautiful   
3                    ZAYN, Sia  Dusk Till Dawn (feat. Sia) - Radio Edit   
4                  Demi Lovato                             Heart Attack   

                    album release_date  popularity  \
0  Inner Monologue Part 1   2019-01-24          85   
1            Don't Go Yet   2021-07-23          87   
2    Know-It-All (Deluxe)   2015-11-13          75   
3            Icarus Falls   2018-12-14          79   
4                    Demi   2013-01-01          82   

                                                href  danceability  energy  \
0  https://api.spotify.com/v1/tracks/5WtfUKzXircv...         0.516   0.467   
1  https://api.spotify.com/v1/tracks/1058fW9H3fZA...         0.666   0.796   
2  https://api.spotify.com/v1/tracks/0prNGof3XqfT...         0.573   0.739   
3  https://api.spotify.com/v1/tracks/3e7sxremeOE3...         0.259   0.437   
4  https://api.spotify.com/v1/tracks/1V6gIisPpYqg...         0.504   0.785   

    key  loudness  ...  liveness  valence    tempo            type  \
0   0.0    -6.184  ...    0.0853   0.3860  132.861  audio_features   
1  10.0    -6.967  ...    0.0442   0.6100  110.108  audio_features   
2   0.0    -5.740  ...    0.1110   0.4510   97.085  audio_features   
3  11.0    -6.589  ...    0.1060   0.0951  180.042  audio_features   
4   8.0    -4.802  ...    0.2390   0.5020  173.968  audio_features   

                       id                                   uri  \
0  5WtfUKzXircvW8l5aaVZWT  spotify:track:5WtfUKzXircvW8l5aaVZWT   
1  1058fW9H3fZA6QjYCdOBad  spotify:track:1058fW9H3fZA6QjYCdOBad   
2  0prNGof3XqfTvNDxHonvdK  spotify:track:0prNGof3XqfTvNDxHonvdK   
3  3e7sxremeOE3wTySiOhGiP  spotify:track:3e7sxremeOE3wTySiOhGiP   
4  1V6gIisPpYqgFeWbMLI0bA  spotify:track:1V6gIisPpYqgFeWbMLI0bA   

                                        analysis_url duration_ms  \
0  https://api.spotify.com/v1/audio-analysis/5Wtf...    173307.0   
1  https://api.spotify.com/v1/audio-analysis/1058...    164842.0   
2  https://api.spotify.com/v1/audio-analysis/0prN...    230227.0   
3  https://api.spotify.com/v1/audio-analysis/3e7s...    239000.0   
4  https://api.spotify.com/v1/audio-analysis/1V6g...    210840.0   

  time_signature genre  
0            4.0   pop  
1            4.0   pop  
2            4.0   pop  
3            4.0   pop  
4            4.0   pop  

[5 rows x 24 columns]

In [30]:
# top_genres = genres.loc[genres.genre.isin(['pop', 'rock', 'rap', 'hip hop', 'edm', 'r&b', 'jazz', 'country', ' metal', 'indie pop', 'classical'])]
# top_genres = genres.loc[genres.genre.isin(genres.genre.unique()[0:50])]
top_genres = genres.loc[genres.genre.isin(['pop', 'rock', 'rap', 'hip hop', 'edm', 'r&b', 'jazz', 'country', ' metal', 'indie rock', 'classical'])]

top_genres.genre.unique()

array(['pop', 'rap', 'rock', 'hip hop', 'edm', 'r&b', 'country',
       'indie rock', 'classical', 'jazz'], dtype=object)

In [31]:
x = pd.DataFrame(top_genres[['acousticness','danceability','energy','instrumentalness','liveness','loudness','speechiness','tempo','valence']])
y = pd.DataFrame(top_genres.genre, columns=['genre'])
y

genre
0       pop
1       pop
2       pop
3       pop
4       pop
...     ...
30595  jazz
30596  jazz
30597  jazz
30598  jazz
30599  jazz

[1000 rows x 1 columns]

In [32]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

(x_train, x_test, y_train, y_test) = train_test_split(x, y, test_size=0.2)
y_train.shape

(800, 1)

In [33]:
tree = DecisionTreeClassifier(criterion="entropy")
tree.fit(x.values, np.array(y).reshape(len(y),))

y_pred = tree.predict(x_test.values)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[18  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  0  0  0  0  0  0  0]
 [ 0  0 22  0  0  0  0  0  0  0]
 [ 0  0  0 24  0  0  0  0  0  0]
 [ 0  0  0  0 17  0  0  0  0  0]
 [ 0  0  0  0  0 21  0  0  0  0]
 [ 0  0  0  0  0  0 18  0  0  0]
 [ 0  0  0  0  0  0  0 23  0  0]
 [ 0  0  0  4  0  0  0  0 16  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
              precision    recall  f1-score   support

   classical       1.00      1.00      1.00        18
     country       1.00      1.00      1.00        17
         edm       1.00      1.00      1.00        22
     hip hop       0.86      1.00      0.92        24
  indie rock       1.00      1.00      1.00        17
        jazz       1.00      1.00      1.00        21
         pop       1.00      1.00      1.00        18
         r&b       1.00      1.00      1.00        23
         rap       1.00      0.80      0.89        20
        rock       1.00      1.00      1.00        20

    accuracy                           0.98       200
   macro avg       

In [34]:
sample_one = tree.predict([[0.235, 0.572, 0.743, 0.00000593, 0.0761, -3.991, 0.12, 170.123, 0.678]])
sample_two = tree.predict([[0.0139, 0.703, 0.834, 0, 0.1, -5.134, 0.0603, 153.97, 0.863]])
sample_three = tree.predict([[0.876, 0.517, 0.0917, 0.629, 0.108, -18.395, 0.0336, 95.068, 0.0836]])
sample_four = tree.predict([[0.00764, 0.421, 0.958, 0.269, 0.103, -2.886, 0.0755, 118.192, 0.496]])

print("[Red Velvet - Kingdom Come] is most likely of genre", sample_one)
print("[Denzel Curry - Dynasties & Dystopia] is most likely of genre", sample_two)
print("[Esbjorn Svensson Trio - Where We Used to Live] is most likely of genre", sample_three)
print("[Thank You Scientist - Life of Vermin] is most likely of genre", sample_four)

[Red Velvet - Kingdom Come] is most likely of genre ['pop']
[Denzel Curry - Dynasties & Dystopia] is most likely of genre ['rap']
[Esbjorn Svensson Trio - Where We Used to Live] is most likely of genre ['jazz']
[Thank You Scientist - Life of Vermin] is most likely of genre ['indie rock']


In [35]:
from sklearn.svm import SVC

svclassifier = SVC(kernel="linear")
svclassifier.fit(x_train.values, np.array(y_train).reshape(len(y_train),))
y_pred = svclassifier.predict(x_test.values)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[15  0  0  0  0  3  0  0  0  0]
 [ 0  7  1  0  0  1  3  3  0  2]
 [ 0  1 13  1  0  0  4  0  2  1]
 [ 0  0  0 18  0  0  2  2  1  1]
 [ 0  2  2  0  6  3  2  0  0  2]
 [ 6  2  0  0  1 11  0  0  0  1]
 [ 0  0  0  0  0  1 12  4  0  1]
 [ 0  6  1  1  0  0  4  8  3  0]
 [ 0  1  1  6  1  0  2  0  9  0]
 [ 0  5  2  0  3  0  0  0  1  9]]
              precision    recall  f1-score   support

   classical       0.71      0.83      0.77        18
     country       0.29      0.41      0.34        17
         edm       0.65      0.59      0.62        22
     hip hop       0.69      0.75      0.72        24
  indie rock       0.55      0.35      0.43        17
        jazz       0.58      0.52      0.55        21
         pop       0.41      0.67      0.51        18
         r&b       0.47      0.35      0.40        23
         rap       0.56      0.45      0.50        20
        rock       0.53      0.45      0.49        20

    accuracy                           0.54       200
   macro avg       

In [36]:
sample_one = svclassifier.predict([[0.235, 0.572, 0.743, 0.00000593, 0.0761, -3.991, 0.12, 170.123, 0.678]])
sample_two = svclassifier.predict([[0.0139, 0.703, 0.834, 0, 0.1, -5.134, 0.0603, 153.97, 0.863]])
sample_three = svclassifier.predict([[0.876, 0.517, 0.0917, 0.629, 0.108, -18.395, 0.0336, 95.068, 0.0836]])
sample_four = svclassifier.predict([[0.00764, 0.421, 0.958, 0.269, 0.103, -2.886, 0.0755, 118.192, 0.496]])

print("[Red Velvet - Kingdom Come] is most likely of genre", sample_one)
print("[Denzel Curry - Dynasties & Dystopia] is most likely of genre", sample_two)
print("[Esbjorn Svensson Trio - Where We Used to Live] is most likely of genre", sample_three)
print("[Thank You Scientist - Life of Vermin] is most likely of genre", sample_four)

[Red Velvet - Kingdom Come] is most likely of genre ['pop']
[Denzel Curry - Dynasties & Dystopia] is most likely of genre ['country']
[Esbjorn Svensson Trio - Where We Used to Live] is most likely of genre ['jazz']
[Thank You Scientist - Life of Vermin] is most likely of genre ['edm']


In [37]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(criterion='entropy', n_estimators=100, min_samples_split=11, max_features='auto')
rfc.fit(x_train.values, np.array(y_train).reshape(len(y_train),))
y_pred = rfc.predict(x_test.values)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[16  0  0  0  0  2  0  0  0  0]
 [ 0 10  0  1  1  0  2  2  0  1]
 [ 0  1 15  2  1  0  1  0  1  1]
 [ 0  0  0 17  0  0  1  1  4  1]
 [ 0  3  1  0  9  1  1  0  0  2]
 [ 6  0  0  0  1 11  1  0  0  2]
 [ 0  0  1  1  0  0 11  4  0  1]
 [ 0  4  2  2  0  0  3  6  6  0]
 [ 0  0  2  6  0  0  2  0 10  0]
 [ 0  2  2  0  8  0  0  1  0  7]]
              precision    recall  f1-score   support

   classical       0.73      0.89      0.80        18
     country       0.50      0.59      0.54        17
         edm       0.65      0.68      0.67        22
     hip hop       0.59      0.71      0.64        24
  indie rock       0.45      0.53      0.49        17
        jazz       0.79      0.52      0.63        21
         pop       0.50      0.61      0.55        18
         r&b       0.43      0.26      0.32        23
         rap       0.48      0.50      0.49        20
        rock       0.47      0.35      0.40        20

    accuracy                           0.56       200
   macro avg       

In [38]:
sample_one = rfc.predict([[0.235, 0.572, 0.743, 0.00000593, 0.0761, -3.991, 0.12, 170.123, 0.678]])
sample_two = rfc.predict([[0.0139, 0.703, 0.834, 0, 0.1, -5.134, 0.0603, 153.97, 0.863]])
sample_three = rfc.predict([[0.876, 0.517, 0.0917, 0.629, 0.108, -18.395, 0.0336, 95.068, 0.0836]])
sample_four = rfc.predict([[0.00764, 0.421, 0.958, 0.269, 0.103, -2.886, 0.0755, 118.192, 0.496]])

print("[Red Velvet - Kingdom Come] is most likely of genre", sample_one)
print("[Denzel Curry - Dynasties & Dystopia] is most likely of genre", sample_two)
print("[Esbjorn Svensson Trio - Where We Used to Live] is most likely of genre", sample_three)
print("[Thank You Scientist - Life of Vermin] is most likely of genre", sample_four)

[Red Velvet - Kingdom Come] is most likely of genre ['country']
[Denzel Curry - Dynasties & Dystopia] is most likely of genre ['rap']
[Esbjorn Svensson Trio - Where We Used to Live] is most likely of genre ['jazz']
[Thank You Scientist - Life of Vermin] is most likely of genre ['indie rock']


In [39]:
top_songs_2020 = pd.read_csv('../FormulaOfLove.csv')
top_songs_2020.head()

artists       name                    album release_date  popularity  \
0   TWICE  SCIENTIST  Formula of Love: O+T=<3   2021-11-12          82   
1   TWICE  MOONLIGHT  Formula of Love: O+T=<3   2021-11-12          72   
2   TWICE       ICON  Formula of Love: O+T=<3   2021-11-12          73   
3   TWICE      CRUEL  Formula of Love: O+T=<3   2021-11-12          69   
4   TWICE   REAL YOU  Formula of Love: O+T=<3   2021-11-12          66   

                                                href  danceability  energy  \
0  https://api.spotify.com/v1/tracks/0BJMgVrnWIvg...         0.786   0.858   
1  https://api.spotify.com/v1/tracks/14k4ALBLN2Fj...         0.807   0.704   
2  https://api.spotify.com/v1/tracks/2VdU1ksBKcET...         0.746   0.809   
3  https://api.spotify.com/v1/tracks/139JUU8fJkQo...         0.840   0.827   
4  https://api.spotify.com/v1/tracks/3ax3sc1Rn99Y...         0.858   0.831   

   key  loudness  ...  instrumentalness  liveness  valence    tempo  \
0   11    -3.740  ...               0.0    0.1260    0.649  112.999   
1    5    -5.496  ...               0.0    0.0535    0.961  115.995   
2    6    -3.571  ...               0.0    0.0756    0.816  149.984   
3    9    -2.958  ...               0.0    0.1510    0.820  124.989   
4    9    -3.029  ...               0.0    0.0453    0.886  119.975   

             type                      id  \
0  audio_features  0BJMgVrnWIvgYsjq8KaPeh   
1  audio_features  14k4ALBLN2FjtELYDcQUoi   
2  audio_features  2VdU1ksBKcETBr8BYRHUvB   
3  audio_features  139JUU8fJkQoeHl9nABk9C   
4  audio_features  3ax3sc1Rn99YbjyKT0HALS   

                                    uri  \
0  spotify:track:0BJMgVrnWIvgYsjq8KaPeh   
1  spotify:track:14k4ALBLN2FjtELYDcQUoi   
2  spotify:track:2VdU1ksBKcETBr8BYRHUvB   
3  spotify:track:139JUU8fJkQoeHl9nABk9C   
4  spotify:track:3ax3sc1Rn99YbjyKT0HALS   

                                        analysis_url duration_ms  \
0  https://api.spotify.com/v1/audio-analysis/0BJM...      194600   
1  https://api.spotify.com/v1/audio-analysis/14k4...      219387   
2  https://api.spotify.com/v1/audio-analysis/2VdU...      176160   
3  https://api.spotify.com/v1/audio-analysis/139J...      211427   
4  https://api.spotify.com/v1/audio-analysis/3ax3...      187933   

  time_signature  
0              4  
1              4  
2              4  
3              4  
4              4  

[5 rows x 23 columns]

In [40]:
# ['acousticness','danceability','energy','instrumentalness','liveness','loudness','speechiness','tempo','valence']
for i in range(len(top_songs_2020)):
    print("[" + top_songs_2020.artists.iloc[i] + " - " + top_songs_2020.name.iloc[i] + "] ", end="")
    tree_sample = tree.predict([[top_songs_2020.acousticness.iloc[i], top_songs_2020.danceability.iloc[i], top_songs_2020.energy.iloc[i], top_songs_2020.instrumentalness.iloc[i], top_songs_2020.liveness.iloc[i], top_songs_2020.loudness.iloc[i], top_songs_2020.speechiness.iloc[i], top_songs_2020.tempo.iloc[i], top_songs_2020.valence.iloc[i]]])
    sv_sample = svclassifier.predict([[top_songs_2020.acousticness.iloc[i], top_songs_2020.danceability.iloc[i], top_songs_2020.energy.iloc[i], top_songs_2020.instrumentalness.iloc[i], top_songs_2020.liveness.iloc[i], top_songs_2020.loudness.iloc[i], top_songs_2020.speechiness.iloc[i], top_songs_2020.tempo.iloc[i], top_songs_2020.valence.iloc[i]]])
    rfc_sample = rfc.predict([[top_songs_2020.acousticness.iloc[i], top_songs_2020.danceability.iloc[i], top_songs_2020.energy.iloc[i], top_songs_2020.instrumentalness.iloc[i], top_songs_2020.liveness.iloc[i], top_songs_2020.loudness.iloc[i], top_songs_2020.speechiness.iloc[i], top_songs_2020.tempo.iloc[i], top_songs_2020.valence.iloc[i]]])
    print("is most likely of genre ", tree_sample, sv_sample, rfc_sample)

[TWICE - SCIENTIST] is most likely of genre  ['pop'] ['pop'] ['pop']
[TWICE - MOONLIGHT] is most likely of genre  ['r&b'] ['r&b'] ['pop']
[TWICE - ICON] is most likely of genre  ['pop'] ['pop'] ['rap']
[TWICE - CRUEL] is most likely of genre  ['pop'] ['pop'] ['pop']
[TWICE - REAL YOU] is most likely of genre  ['rap'] ['pop'] ['pop']
[TWICE - F.I.L.A (Fall In Love Again)] is most likely of genre  ['pop'] ['pop'] ['pop']
[TWICE - LAST WALTZ] is most likely of genre  ['rap'] ['pop'] ['rap']
[TWICE - ESPRESSO] is most likely of genre  ['hip hop'] ['hip hop'] ['hip hop']
[TWICE - REWIND] is most likely of genre  ['hip hop'] ['pop'] ['rap']
[TWICE - CACTUS] is most likely of genre  ['pop'] ['edm'] ['country']
[TWICE - PUSH & PULL (JIHYO, SANA, DAHYUN)] is most likely of genre  ['country'] ['pop'] ['hip hop']
[TWICE - HELLO (NAYEON, MOMO, CHAEYOUNG)] is most likely of genre  ['pop'] ['rap'] ['rap']
[TWICE - 1, 3, 2 (JEONGYEON, MINA, TZUYU)] is most likely of genre  ['country'] ['pop'] ['pop']